name: travel_hour
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  
  animated_bottom_navigation_bar: ^1.1.0+1
  cached_network_image: ^3.2.2
  cloud_firestore: ^4.3.1
  cupertino_icons: ^1.0.5
  dots_indicator: ^2.1.0
  easy_localization: ^3.0.1
  firebase_analytics: ^10.1.0
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  firebase_storage: ^11.0.10
  firebase_in_app_messaging: ^0.7.0+10
  flare_flutter: ^3.0.2
  flutter_html: ^3.0.0-alpha.5
  flutter_polyline_points: ^1.0.0
  geo: ^0.3.0
  google_fonts: ^4.0.3
  google_maps_flutter: ^2.2.0
  google_sign_in: ^6.0.2	
  html_unescape: ^2.0.0
  http: ^0.13.5
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  launch_review: ^3.0.1
  line_icons: ^2.0.1
  package_info: ^2.0.2
  provider: ^6.0.3
  share: ^2.0.4
  shared_preferences: ^2.0.15
  skeleton_text: ^3.0.0
  sliding_up_panel: ^2.0.0+1
  url_launcher: ^6.1.5
  the_apple_sign_in: ^1.1.1
  fluttertoast: ^8.0.9
  flutter_facebook_auth: ^5.0.7
  flutter_web_browser: ^0.17.1
  google_mobile_ads: ^2.0.1
  # facebook_audience_network: ^1.0.1
  carousel_pro_nullsafety: ^1.0.2
  pod_player: ^0.1.0
  app_settings: ^4.2.0
  # flutter_icons: ^1.1.0
  flutter_feather_icons: ^2.0.0+1
  md2_tab_indicator:
    git:
      url: https://github.com/westdabestdb/md2_tab_indicator
 
  audioplayers: ^3.0.1
  geofence_service: ^3.5.0
  flutter_local_notifications: ^8.2.0
  assets_audio_player: ^3.0.6
  activity_recognition_flutter: ^4.2.0
  font_awesome_flutter: ^10.4.0

 

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.11.0"
  change_app_package_name: ^1.1.0




flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"






flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/flr/
    - assets/translations/

    

  fonts:

    - family: Muli
      fonts:
        # - asset: fonts/Montserrat-Light.ttf
        #   weight: 400
        - asset: assets/fonts/Muli-Regular.ttf
          weight: 500
        - asset: assets/fonts/Muli-Medium.ttf
          weight: 600
        - asset: assets/fonts/Muli-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Muli-Bold.ttf
          weight: 800


    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 900


    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 500
